-- Create CALENDAR_MONTH table
CREATE TABLE calendar_month (
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15) NOT NULL UNIQUE,
	short_name VARCHAR(5) NOT NULL UNIQUE,
	quarter TINYINT UNSIGNED NOT NULL
);
