-- Create COUNTY table
CREATE TABLE county (
	id SMALLINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL UNIQUE,
	fips VARCHAR(12) NOT NULL UNIQUE,
	state_id TINYINT UNSIGNED NOT NULL,

	FOREIGN KEY (state_id) REFERENCES state (id)
);
