-- Create evictions table
CREATE TABLE evictions (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	calendar_date_id SMALLINT UNSIGNED NOT NULL,
	city_id SMALLINT UNSIGNED NOT NULL,
	filings SMALLINT UNSIGNED NOT NULL,
	geoid VARCHAR(15) NULL
);
